name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or whichever branch you want to auto-deploy

permissions:
  contents: 'read'
  id-token: 'write'  # Required for Workload Identity Federation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: asia-east1-docker.pkg.dev/tensile-oarlock-461809-u3/yoli-repo/yoliwedding:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: yoliwedding
          region: asia-east1
          image: asia-east1-docker.pkg.dev/tensile-oarlock-461809-u3/yoli-repo/yoliwedding:latest
